COMMON: &common
  SECRET_KEY: insecure
  APP_IP: '127.0.0.1'
  APP_PORT: 5000

  UPLOADS_DEFAULT_DEST: 'src/uploads'
  UPLOADS_DEFAULT_URL: 'http://127.0.0.1:5000/uploads'

  SQLALCHEMY_DATABASE_URI: 'sqlite:///db/db-test.sqlite'
  SQLALCHEMY_COMMIT_ON_TEARDOWN: True
  SQLALCHEMY_TRACK_MODIFICATIONS: False

DEVELOPMENT: &development
  <<: *common
  DEBUG: True

PRODUCTION: &production
  <<: *common
  DEBUG: False
  SECRET_KEY: 1d94e52c-1c89-4515-b87a-f48cf3cb7f0b

  UPLOADS_DEFAULT_URL: 'http://127.0.0.1:8080/uploads'
  SQLALCHEMY_DATABASE_URI: 'sqlite:///db/db.sqlite'
  SQLALCHEMY_COMMIT_ON_TEARDOWN: True
  SQLALCHEMY_TRACK_MODIFICATIONS: False
